blogs/urls.py
from django.urls import path

from blogs import views

urlpatterns = [
    path('', views.list),
    path('search/', views.search),
    path('<int:id>/', views.detail),
    path('<int:id>/review/', views.review),

    path('login/', views.mylogin),
    path('logout/', views.mylogout),
    path('signup/', views.mysignup),



]

polls/urls.py
from django.urls import path

from polls import views

urlpatterns = [
    path('', views.list),
    path('<int:id>/', views.detail),
    path('<int:id>/vote/', views.vote),

]

website/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from polls import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('polls/', include("polls.urls")),
    path('blogs/', include("blogs.urls")),
]

blogs/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Article(models.Model):
    title       = models.CharField(max_length=250)
    description = models.TextField()
    author      = models.CharField(max_length=250)
    created     = models.DateTimeField(auto_now_add=True)
    modified    = models.DateTimeField(auto_now=True)
    published   = models.BooleanField(default=True)
    view        = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Review(models.Model):
    rate = models.IntegerField(default=1)
    review = models.TextField(blank=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review

polls/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    text = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=250)
    vote = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

blogs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from blogs.models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ["rate", "review"]



class UserSignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]


class LoginForm(forms.Form):
    username = forms.CharField(max_length=250)
    password = forms.CharField(max_length=250, widget=forms.PasswordInput)

blogs/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect


# Create your views here.
from blogs.forms import ReviewForm, UserSignupForm, LoginForm
from blogs.models import Article


def list(req):
    datas = Article.objects.filter(published=True)
    return render(req, "blogs/index.html", {"datas":datas})

def search(req):
    q = req.GET["q"]
    datas = Article.objects.filter(published=True, title__contains=q)
    return render(req, "blogs/index.html", {"datas":datas})

def detail(req, id):
    article = Article.objects.get(id=id)
    article.view += 1
    article.save()
    form = ReviewForm()
    return render(req, "blogs/detail.html", {"article":article,"form":form})

def review(req, id):
    if req.method == "POST":
        form = ReviewForm(req.POST)
        myreview = form.save(commit=False)
        if myreview.rate <= 5 and myreview.rate >= 1:
            myreview.article = Article.objects.get(id=id)
            myreview.user = req.user
            myreview.save()


    return redirect("/blogs/%d/" % id)

def mylogin(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user:
            # check for user startus if user.is
            login(request, user)
            return redirect("/blogs/")
    else:
        form = LoginForm()
    return render(request, "blogs/login.html", {"form":form})

def mylogout(request):
    logout(request)
    return redirect("/blogs/")

def mysignup(request):

    if request.method == "POST":
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # procces for initial user
            user.save()
            return redirect("/blogs/")

    else:
        form = UserSignupForm()
    return render(request, "blogs/signup.html", {"form":form})

polls/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
# Create your views here.
from polls import models


def home(req):
    return HttpResponse("Hello World")

def list(req):
    questions = models.Question.objects.all()
    context = {}
    context["questions"] = questions
    context["hello"] = "this is hello"
    return render(req, "polls/home.html", context)

def detail(req, id):
    question = models.Question.objects.get(id=id)
    question.views += 1
    question.save()
    context = {"question":question}
    return render(req, "polls/detail.html", context)

def vote(req, id):
    # increase vote count
    print("question id", id)
    choice_id = req.POST["choice"]
    print("selected choice id", choice_id)

    question = models.Question.objects.get(id=id)
    choice = question.choice_set.get(id=choice_id)

    choice.vote += 1
    choice.save()

    # return redirect("/")
    return redirect("/polls/" + str(id) + "/")
    # return redirect("/polls/{}/".format(id))

blogs/templates/blogs/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>{% block title %}Default Title{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">Navbar</a>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                {% if user.is_authenticated %}
              <a class="nav-link" href="/blogs/logout">Logout</a>
                    {% else %}
                    <a class="nav-link" href="/blogs/login">Login</a>
                {% endif %}
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{% if user.is_authenticated %}{{ user.username }}{% else %}Guest{% endif %}</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" action="/blogs/search/">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
      <div class="row">
        <div class="col-3">
          <div class="alert alert-success" role="alert">
            A simple primary alert—check it out!
          </div>
        </div>
        <div class="col-9">
{#          <div class="alert alert-success" role="alert">#}
{#            A simple primary alert—check it out!#}
{#          </div>#}
          {% block content %}
              <div class="row">
                <div class="col-6">6 cols</div>
                <div class="col-6">6 cols</div>
              </div>
          {% endblock %}
        </div>

      </div>


    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

blogs/templates/blogs/detail.html
{% extends "blogs/base.html" %}

{% block title %}{{ article.title|title }}{% endblock %}

{% block content %}
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title">{{ article.title|title }}</h5>
        <p class="card-text">{{ article.description }}</p>
          <p class="card-text">Views {{ article.view }}</p>
          <p class="card-text">Author {{ article.author }}</p>
      </div>
    </div>

    <hr>
    <h3>Total reviews : {{ article.review_set.all|length }}</h3>

    {% for review in article.review_set.all %}
        <div class="card">
          <div class="card-header">
            {{ review.rate }} stars
          </div>
          <div class="card-body">
            <blockquote class="blockquote mb-0">
              <p>{{ review.review }}</p>
              <footer class="blockquote-footer">{{ review.created|timesince }} ago by {{ review.user.username }}</footer>
            </blockquote>
          </div>
        </div>
    {% endfor %}

{#  create form  #}

    <form method="post" class="m-3" action="/blogs/{{ article.id }}/review/">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit Review">
    </form>

{% endblock %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}


{%  block content %}
<h2>Current time is {% now "Y M d H:i:s" %}</h2>
    Total count {{ datas|length }}
{% for article in datas %}


    <div class="card text-center">
      <div class="card-header">
        Featured
      </div>
      <div class="card-body">
        <h5 class="card-title">{{ article.title|title }}</h5>
        <p class="card-text">{{ article.description|truncatewords:5 }}</p>
        <a href="/blogs/{{ article.id }}" class="btn btn-primary">View More</a>
      </div>
      <div class="card-footer text-muted">
        {{ article.created|timesince}}
      </div>
    </div>

{% empty %}
    {% lorem 10 %}
<h1>No content available</h1>
{% endfor %}
    var is {{ newvar|default:"default" }}.

{% endblock %}

blogs/templates/blogs/login.html
<center>
    <h2>Login Form</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>

</center>

blogs/templates/blogs/signup.html
<center>
    <h2>Signup Form</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Signup">
    </form>

</center>

polls/templates/polls/base.html
<!DOCTYPE html>

<html lang="en-us" >
<head>
<title>{% block mytitle %}Default Title{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
<link rel="stylesheet" type="text/css" href="/static/admin/css/dashboard.css">


    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=" dashboard"
  data-admin-utc-offset="20700">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a href="/admin/">Django administration</a></h1>

        </div>


        <div id="user-tools">

                Welcome,
                <strong>hereshem</strong>.



                    <a href="/">View site</a> /


                <a href="/admin/password_change/">Change password</a> /

                <a href="/admin/logout/">Log out</a>

        </div>



    </div>
    <!-- END Header -->

    {% block mycontent %}{% endblock %}

    <div id="footer">This is Footer</div>


</div>
<!-- END Container -->

</body>
</html>

polls/templates/polls/detail.html
{% extends "polls/base.html" %}
{% block mytitle %}{{ question.text }}{% endblock %}
{% block mycontent %}
<center>
<h1>{{ question.text }}</h1>

<form method="post" action="/polls/{{ question.id }}/vote/">
{% csrf_token %}

    {% for ch in question.choice_set.all %}
        <p>
            <input type="radio" name="choice" value="{{ ch.id }}">
            <b>{{ ch.text }} - {{ ch.vote }}</b>
        </p>
    {% endfor %}
    <input type="submit" value="Submit Vote">
</form>
</center>
{% endblock %}

polls/templates/polls/home.html
{% extends "polls/base.html" %}

{% block mycontent %}
    {% for q in questions %}
        <p>
        <a href="/polls/{{ q.id }}"> {{ q.text }} </a>
        </p>
    {% endfor %}
{% endblock %}

{%  block mytitle %}List page{% endblock %}